sudo: false

language: node_js

node_js:
  - 10
  - 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

after_success:
  - yarn test --coverage
  - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info

cache:
  yarn: true
  directories:
    - $HOME/.cache
    - node_modules
